# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: "Home Server"

steps:
  - task: Cache@2
    displayName: 'Cache .next/cache'
    inputs:
      key: next | $(Agent.OS) | package-lock.json
      path: '$(System.DefaultWorkingDirectory)/.next/cache'
  - task: Docker@2
    inputs:
      containerRegistry: 'azure'
      repository: 'thejguih/nextcondo'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
