# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool: "Home Server"

stages:
- stage: build
  jobs:
  - job: run_build
    pool: "Home Server"
    steps:
    - task: Cache@2
      displayName: 'Cache .next/cache'
      inputs:
        key: next | $(Agent.OS) | package-lock.json
        path: '$(System.DefaultWorkingDirectory)/.next/cache'
    - script: |
        npm install
      displayName: 'install dependencies'
    - script: |
        npm run build
      displayName: 'npm build'
    - task: CopyFiles@2
      displayName: 'Copy .next/standalone to staging directory'
      inputs:
        SourceFolder: '.next/standalone'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/standalone'
    - task: CopyFiles@2
      displayName: 'Copy .next/static to staging directory'
      inputs:
        SourceFolder: '.next/static'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/static'
    - publish: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Publish Nextapp'
      artifact: nextapp
