services:
  nextcondo-frontend:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:80
    networks:
      - nextcondotest

networks: 
  nextcondotest:
    external: true