import type { Metadata, Viewport } from "next";
import "../globals.css";
import ThemeRegistry from "@/src/theme-registry/components/theme-registry";
import { AuthBoundary } from "@/src/shared/authentication/components/boundary";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <AuthBoundary>{children}</AuthBoundary>
        </ThemeRegistry>
      </body>
    </html>
  );
}
