import type { Metadata, Viewport } from "next";
import "../globals.css";
import ThemeRegistry from "@/src/theme-registry/components/theme-registry";
import { AuthBoundary } from "@/src/shared/authentication/components/boundary";
import { Locale } from "@/i18n-config";
import { LocaleProvider } from "@/src/localization/client/LangProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: {
    lang: Locale;
  };
}>) {
  return (
    <html lang={lang}>
      <body>
        <ThemeRegistry>
          <LocaleProvider lang={lang}>
            <AuthBoundary>{children}</AuthBoundary>
          </LocaleProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
